# Generated by Django 2.2.2 on 2019-06-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(blank=True, upload_to='images/%y/%m/%d'),
        ),
    ]
